### ISSUE TITLE
`.getchildren` is removed in Python 3.9

### ISSUE THREAD

**Issue by nikmolnar** [consbio/parserutils#1]
The library contains a couple references to the `xml.etree.ElementTree.Element.getchildren` method. This method was deprecated in Python 3.2 and finally removed in Python 3.9. This is causing the library to break in 3.9.

Related to https://github.com/consbio/gis-metadata-parser/issues/4

**Comment by dharvey-consbio** [comment]
This has been completed and deployed as version 1.2.3.
